### ISSUE TITLE
Datasheet for SR6 / HR6

### ISSUE THREAD

**Issue by tberezowski** [ap--/libseabreeze#3]
I noticed that SR2 and SR4 support were recently added. I would like to add support for SR6 and HR6 myself. Unfortunately, I cannot find a datasheet. These models are also not listed in the original [SeaBreeze](https://www.oceaninsight.com/globalassets/catalog-blocks-and-images/software-downloads-installers/javadocs-api/seabreeze/html/files.html). Does anyone have these datasheets or any information that would help me to add support for these devices?

**Comment by tberezowski** [comment]
my misstake

**Comment by ap--** [comment]
see [ap--/python-seabreeze#224](https://github.com/ap--/python-seabreeze/issues/224)
